name: Test
on: [push]
jobs:
  on_build_actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: 
          cd $GITHUB_WORKSPACE
      - name: Run Tests
        run: python -m unittest tests/*.py